### ISSUE TITLE
Need Help: SSE HTML fragment rendering with Thymeleaf is not working 

### ISSUE THREAD

**Issue by xmlking** [danielfernandez/reactive-matchday#1]
I am following your project as an example to  render HTML via SSE with Thymeleaf fragment, but it is not working. Browser/EventSource connects to endpoint but no data is received. 
As a work around I am using JSON  SSE and updating  HTML with JavaScript. 

https://github.com/xmlking/reactive-apps/blob/master/ui-app/src/main/kotlin/com/example/UiApplication.kt#L118

wonder if you can help me if I am missing something.

**Comment by danielfernandez** [comment]
It works for me. Can you confirm which browser are you using? is this MS Edge, maybe?

**Comment by danielfernandez** [comment]
And with *it* works, I mean the application in this repository, `reactive-matchday`. Or maybe you are referring to a different application?

**Comment by xmlking** [comment]
Not your app. My app provided link above is not working :(

**Comment by danielfernandez** [comment]
Well, it's difficult to know what can be happening in your application from my side, and my understanding of Kotlin is very limited.

Anyway, could you confirm if your `.log()` on the data stream actually outputs nothing (after setting the right log level at the app) and also, at the browser, if you use Chrome's DevTools -> Network -> Click on the specific `EventSource` connection... do you see the stream of events there? so can you confirm that *nothing* is being sent at all (and if you don't see any stream logging, that actually the stream isn't even been subscribed at the server)?

Also, what is your operating system and server? if you are not receiving anything at the browser and you are using Tomcat, could you please try Netty (just in case there is a server-side buffering issue involved, which to be honest would seem the most probable here...)?
